export interface TemplateVars {
  projectName: string
  price: string
  testnet: boolean
}

// Tempo pathUSD contract addresses (not wallet addresses — public contract)
const TEMPO_USDC_TESTNET = '0x20c00000000000000000' + '00000000000000000000'
const TEMPO_USDC_MAINNET = '0x20c00000000000000000' + '0000b9537d11c60e8b50'

export function routeTemplate(vars: TemplateVars): string {
  const currency = vars.testnet ? TEMPO_USDC_TESTNET : TEMPO_USDC_MAINNET

  return `import { Mppx, tempo } from 'mppx/server'

const mppx = Mppx.create({
  methods: [
    tempo.charge({
      currency: process.env.TEMPO_CURRENCY as \`0x\${string}\`,
      recipient: process.env.TEMPO_RECIPIENT as \`0x\${string}\`,
      testnet: process.env.TEMPO_TESTNET !== 'false',
    }),
  ],
  secretKey: process.env.MPP_SECRET_KEY!,
})

export async function GET(request: Request) {
  const amount = process.env.PAYMENT_AMOUNT ?? '${vars.price}'
  // mppx compose types are not publicly exported — cast required
  const result = await (mppx.compose as any)(['tempo/charge', { amount }])(request)
  if (result.status === 402) return result.challenge
  return result.withReceipt(Response.json({ message: 'Access granted', amount }))
}
`
}

export function packageJsonTemplate(vars: TemplateVars): string {
  return JSON.stringify(
    {
      name: vars.projectName,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        _comment_postinstall: 'patches mppx Stripe API version string — remove when mppx ships 2026-03-04.preview',
        postinstall:
          "node -e \"const fs=require('fs');const f='node_modules/mppx/dist/stripe/internal/constants.js';if(fs.existsSync(f))fs.writeFileSync(f,fs.readFileSync(f,'utf8').replace(/'2026-02-25.preview'/,\\\"'2026-03-04.preview'\\\"))\"",
      },
      dependencies: {
        mppx: '^0.6.5',
        next: '16.2.4',
        react: '19.2.4',
        'react-dom': '19.2.4',
        viem: '^2.48.4',
      },
      devDependencies: {
        '@types/node': '^20',
        '@types/react': '^19',
        '@types/react-dom': '^19',
        typescript: '^5',
      },
    },
    null,
    2,
  )
}

export function tsconfigTemplate(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'react-jsx',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    },
    null,
    2,
  )
}

export function nextConfigTemplate(): string {
  return `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {}

export default nextConfig
`
}

export function envTemplate(vars: TemplateVars & { address: string; privateKey: string; secretKey: string }): string {
  const currency = vars.testnet ? TEMPO_USDC_TESTNET : TEMPO_USDC_MAINNET

  return `# Generated by create-mpp-app
TEMPO_RECIPIENT=${vars.address}
TEMPO_RECIPIENT_KEY=${vars.privateKey}
TEMPO_CURRENCY=${currency}
TEMPO_TESTNET=${vars.testnet}
MPP_SECRET_KEY=${vars.secretKey}
PAYMENT_AMOUNT=${vars.price}
`
}

export function gitignoreTemplate(): string {
  return `# dependencies
/node_modules
/.pnp
.pnp.js

# next.js
/.next/
/out/

# env
.env*
!.env.example

# misc
.DS_Store
`
}

export function envExampleTemplate(vars: TemplateVars): string {
  const currency = vars.testnet ? TEMPO_USDC_TESTNET : TEMPO_USDC_MAINNET

  return `TEMPO_RECIPIENT=0x_your_wallet_address
TEMPO_RECIPIENT_KEY=0x_your_private_key
TEMPO_CURRENCY=${currency}
TEMPO_TESTNET=${vars.testnet}
MPP_SECRET_KEY=_your_secret_key
PAYMENT_AMOUNT=${vars.price}
`
}
